name: Commit Lint

on:
  workflow_call: # Trigger pro reusable workflow
    inputs:
      branch:
        required: false
        type: string
        default: "main"
  pull_request:
    types: [opened, synchronize, edited]
  push:
    branches:
      - master
      - main
      - develop
      - feature/**
      - release/**
      - test/**
      - bugfix/**

jobs:
  lint-commits:
    uses: gouef/github-lib-template/.github/workflows/shared_commit-lint.yml@main
