name: Generate contributors

on:
  workflow_dispatch:
    inputs:
      excludeBot:
        description: "Exclude actions@github.com from contributors"
        required: false
        type: boolean
        default: false
      notGenerateContributorsMd:
        required: false
        type: boolean
        default: false
        description: "Not commit CONTRIBUTORS.md ?"
  schedule:
    - cron: '0 0 * * 1'
  pull_request:
    types: [ opened, synchronize, edited ]
  push:
    branches:
      - master
      - main
      - develop
      - feature/**
      - release/**
      - test/**
      - bugfix/**

jobs:
  update-contributors:
    uses: gouef/github-lib-template/.github/workflows/shared_contributors.yml@main
    with:
      excludeBot: ${{ inputs.excludeBot || false}}
      notGenerateContributorsMd: ${{ inputs.notGenerateContributorsMd || false }}
